//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseRacing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> DamId { get; set; }
        public Nullable<int> SireId { get; set; }
        public Nullable<int> ColourId { get; set; }
        public int CategoryId { get; set; }
        public int GenderId { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> AcqusitionId { get; set; }
    }
}
